// Generates docs/shortcuts.md from the real command table.
//
// It is generated rather than written because the table is already the single
// source that feeds the palette, the in-app cheatsheet (Ctrl+/) and the key
// bindings — CLAUDE.md's "one list feeds both" rule, which is what keeps the
// shortcut shown beside a command identical to the one that fires. A
// hand-maintained doc would be a fourth copy, and the only one nothing checks:
// add a command, forget the doc, and the doc is quietly wrong for as long as
// nobody runs it.
//
// `docs_test.ts` regenerates and compares, so a forgotten `deno task docs`
// fails the gate instead of shipping. Both call renderShortcuts(), so the test
// cannot pass by agreeing with a stale generator.
//
// Importable with no DOM, which is the same property commands_test.ts relies
// on: COMMAND_SPECS is a plain array literal and nothing at module scope in
// controlCommands.ts touches the document.

import {
  applyPadBindings,
  formatShortcut,
} from "../src/frontend/scripts/commands.ts";
import { COMMAND_GROUPS } from "../src/frontend/scripts/commands.ts";
import { COMMAND_SPECS } from "../src/frontend/scripts/controlCommands.ts";
import { PAD_BINDINGS, PAD_LABELS } from "../src/frontend/scripts/gamepad.ts";

export const SHORTCUTS_PATH = "docs/shortcuts.md";

/** Escape the pipe, which is the one character that would break a cell. */
function cell(text: string): string {
  return text.replaceAll("|", "\\|");
}

export function renderShortcuts(): string {
  const specs = applyPadBindings(COMMAND_SPECS, PAD_BINDINGS, PAD_LABELS);

  const out: string[] = [
    "<!-- Generated by tools/gen-docs.ts from COMMAND_SPECS. Do not edit:",
    "     run `deno task docs`. docs_test.ts fails if this is out of date. -->",
    "",
    "# Keyboard and controller reference",
    "",
    "Every command, grouped as the palette groups them. **Ctrl+K** opens the",
    "palette and **Ctrl+/** lists the bound ones without leaving the page — both",
    "read this same table, so what is shown beside a command is what fires.",
    "",
    "On a Mac, `Ctrl` here means `Cmd`.",
    "",
    "A blank **Keys** cell means the command is palette-only, which is",
    "deliberate for anything reached once while setting up rather than mid-",
    "service. See [operating.md](operating.md) for what the controller's",
    "throttles and stick do, and [why some chords are unavailable](#unavailable).",
    "",
  ];

  for (const group of COMMAND_GROUPS) {
    const rows = specs.filter((s) => s.group === group);
    if (rows.length === 0) continue;
    out.push(`## ${group}`, "");
    out.push("| Command | Keys | Pad |", "| --- | --- | --- |");
    for (const s of rows) {
      const keys = s.shortcut
        ? `\`${formatShortcut(s.shortcut, { apple: false })}\``
        : "";
      out.push(`| ${cell(s.label)} | ${keys} | ${s.pad ?? ""} |`);
    }
    out.push("");
  }

  out.push(
    "## Unavailable by design {#unavailable}",
    "",
    "`Ctrl+0`, `Ctrl+=` and `Ctrl+-` are browser zoom, which Chrome handles",
    "above the page: `preventDefault` does not stop them, so a binding there",
    "looks right and never fires. The text-size and speed-zero commands use",
    "`Ctrl+Alt+…` instead. `Ctrl+Shift+N/O/R/T/W` are browser-owned the same",
    "way.",
    "",
    "Anything carrying `Alt` is bound to a *physical* key rather than a",
    "character, because on macOS `Option+P` is `π` and a binding written as a",
    "letter would silently never match.",
    "",
  );

  return out.join("\n");
}

if (import.meta.main) {
  const text = renderShortcuts();
  await Deno.writeTextFile(SHORTCUTS_PATH, text);
  console.log(`wrote ${SHORTCUTS_PATH} (${text.split("\n").length} lines)`);
}
